openapi: 3.0.0
info:
  title: reading-list-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /validacion/prueba:
    get:
      tags:
        - default
      summary: path prueba
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

